title: South Maroubra Dolphins
subtitle: Winter Swimming Club
email: admin@southmaroubradolphins.com
description: The South Maroubra Dolphins is a winter swimming club that meets at Wylie's Baths from the first Sunday in May until the last Sunday in September
baseurl: "/south-maroubra-dolphins"
url: "https://robertlove.github.io"
twitter: southmaroubradolphins
language: en
region: AU
theme_color: "#7DC7E9"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-redirect-from

exclude:
  - LICENSE
  - Rakefile
  - README.md

permalink: /:title

sass:
  style: :compressed