title: South Maroubra Dolphins
subtitle: Winter Swimming Club
email: admin@southmaroubradolphins.com
description: The South Maroubra Dolphins is a winter swimming club that meets at Wylie's Baths from the first Sunday in May until the last Sunday in September
baseurl: "/south-maroubra-dolphins"
url: "https://robertlove.github.io"
twitter: southmaroubradolphins
language: en
region: AU

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

permalink: /:title

sass:
  style: :compressed

source: _source