title: South Maroubra Dolphins
subtitle: Winter Swimming Club
email: admin@southmaroubradolphins.com
description: The South Maroubra Dolphins is a winter swimming club that meets at Wylie's Baths from the first Sunday in May until mid September
baseurl: "/south-maroubra-dolphins"
url: "https://robertlove.github.io"
language: en
region: AU
date_format: "%A, %e %B %Y"
time_format: "%l:%M %P"
theme_color: "#7DC7E9"

plugins:
  - jekyll-redirect-from
  - jekyll-target-blank

exclude:
  - LICENSE
  - Rakefile
  - README.md

permalink: /:title

redirect_from:
  json: false
