title: South Maroubra Dolphins
subtitle: Winter Swimming Club
email: admin@southmaroubradolphins.com
description: The South Maroubra Dolphins is a winter swimming club that meets at Wylie's Baths from the first Sunday in May until the last Sunday in September
baseurl: ""
url: "https://robertlove.github.io/south-maroubra-dolphins/"
twitter: southmaroubradolphins